version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: app
        uid: 1000
    image: php:8.0-fpm
    container_name: bible-reading-php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - .docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - bible-reading-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: bible-reading-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "39080:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - bible-reading-network

  #MySQL Service
  mysql:
    image: mariadb:10.5.9
    container_name: bible-reading-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bible_reading
      MYSQL_ROOT_PASSWORD: here_is_root_password
      MYSQL_USER: bible_reading
      MYSQL_PASSWORD: here_is_user_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./.docker/mysql/data/:/var/lib/mysql/data
      #- ./.docker/mysql/conf:/etc/mysql/conf/my.cnf
    networks:
      - bible-reading-network

  #PHP MyAdmin - web GUI tool for MySQL
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bible-reading-myadmin
    ports:
      - 39180:80
    environment:
      UPLOAD_LIMIT: 1024M
      PMA_HOST: mysql
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql/data
      - ./.docker/mysql/conf/my.cnf:/etc/mysql/conf/my.cnf
    networks:
      - bible-reading-network

#Docker Networks
networks:
  bible-reading-network:
    driver: bridge
