version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: app
        uid: 1000
    image: php:7.4-fpm
    container_name: bible-reading-php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - .docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - bible-reading-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: bible-reading-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "57280:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - bible-reading-network

#Docker Networks
networks:
  bible-reading-network:
    driver: bridge
